### ISSUE TITLE
Réalisation du bandeau Cookie

### ISSUE THREAD

**Issue by OMoukoko** [SocialGouv/monsuivipsy-site#22]
Bonjour l'équipe,

Nous revenons vers vous pour la réalisation du bandeau cookie du site Monsuivipsy qui n'est à ce jour pas réalisée.

<img width="1291" alt="Capture d’écran 2021-02-18 à 16 35 44" src="https://user-images.githubusercontent.com/79263610/108380701-62a12e80-7207-11eb-8d38-2da077c70d62.png">

Vous pourrez trouver dans le Nextcloud de la Fabrique une recommandation visant à vous accompagner dans la mise en oeuvre de ce bandeau.
Sa nécessité dépendra essentiellement de l'utilisation faite du cookie : OpenStreetMap. Pourriez vous nous dire quelle utilisation en faite ? 

A votre disposition pour toute question,

Très cordialement,

Osiris Moukoko,
NumériCité

**Comment by revolunet** [comment]
Bonjour, OpenStreetMap est utilisé en bas de page pour afficher la localisation de "Établissement Public de Santé Barthélémy Durand". A priori cela ne nécessite pas de cookie ?

**Comment by OMoukoko** [comment]
Bonjour @revolunet ,

A priori, si OpenStreetMap est utilisée pour afficher la localisation de Etablissement Public de santé Barthélémy Durand, il n'y a pas de consentement nécessaire, ni de bandeau cookie le cookie n'étant pas de mesure d'audience, ni de tracking. Néanmoins, il nous faudra quand même faire une mention d'information à ce sujet dans la future politique de confidentialité.

Vous pouvez donc le conserver.

Très cordialement,

Osiris Moukoko Priso, 
Numéricité
